//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWithEFCache
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircraft
    {
        public int Id { get; set; }
        public string EquipmentCode { get; set; }
        public string Airline_Code { get; set; }
    
        public virtual Airline Airline { get; set; }
    }
}
